name: CI For PyDnD

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 19.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: | 
          cd frontend/pydnd
          npm install
      - name: npm ci
        run: | 
          cd frontend/pydnd
          npm ci
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          cache: 'pip'
      - run: pip install -r backend/requirements.txt
      - name: Run tests
        continue-on-error: true
        run: |
          cd backend
          python -m unittest discover -s tests -p "test*.py" || true
  